### ISSUE TITLE
Restarting every one minute

### ISSUE THREAD

**Issue by batikiotis** [nightshift2k/binance-proxy#6]
The contrainer restarts every 1 minute. The log is saying
`level=fatal msg="unknown flag `e' - unknown flag"`

I use this 
```
  exchange-proxy:
    image: nightshift2k/binance-proxy:latest
    restart: unless-stopped
    container_name: exchange-proxy
    command: -verbose 0
```
one my docker-compose.yml
